gelfcore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views.generic.base import RedirectView

from gelfmp.admin import admin_site
from gelfmp.jobs.views import router as jobs_router
from gelfmp.views import router as gelfmp_router

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('assets/favicon.ico'))),
    path('api/', include('gelfmp.api.urls')),
    path('admin/', admin_site.urls),
]

urlpatterns.extend(jobs_router.urls)
urlpatterns.extend(gelfmp_router.urls)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gelfmp/models/contact.py
from django.db import models

from gelfmp.utils import validators
from gelfmp.utils.normalization import normalize_name, normalize_phone

from .base_model import BaseModel
from .choices import ContactType


class Contact(BaseModel):
    name = models.CharField(max_length=200, verbose_name='Nome')
    cpf = models.CharField(
        max_length=14,
        blank=True,
        null=True,
        validators=[validators.validate_cpf_cnpj],
        verbose_name='CPF',
    )

    email = models.EmailField(null=True, blank=True, verbose_name='Email')
    contact_type = models.CharField(max_length=50, choices=ContactType.choices, verbose_name='Função')

    primary_phone = models.CharField(max_length=20, verbose_name='Telefone Principal', null=True, blank=True)
    secondary_phone = models.CharField(max_length=20, verbose_name='Telefone Secundário', null=True, blank=True)

    supplier = models.ForeignKey(
        'Supplier',
        on_delete=models.CASCADE,
        related_name='contacts',
        verbose_name='Fornecedor',
    )

    def clean(self):
        self.primary_phone = normalize_phone(self.primary_phone)
        self.secondary_phone = normalize_phone(self.secondary_phone)
        self.name = normalize_name(self.name)

        return super().clean()

    def __str__(self):
        return f'{self.contact_type} - {self.name}'

    class Meta:
        verbose_name = 'Contato'
        verbose_name_plural = 'Contatos'

gelfmp/models/document.py
import os

from django.db import models
from django.forms import ValidationError

from gelfmp.services import geojson
from gelfmp.utils import dtutils, validators
from gelfmp.utils.functions import handle_file_cleanup, handle_file_cleanup_on_delete
from gelfmp.utils.normalization import normalize_file_and_folder

from .base_model import BaseModel
from .choices import DocumentType


class Document(BaseModel):
    def upload_to(instance, filename):
        safe_filename = normalize_file_and_folder(filename)
        safe_corporate_name = normalize_file_and_folder(instance.supplier.corporate_name)

        return f'FORNECEDORES/{safe_corporate_name}/DOCUMENTOS/{safe_filename}'

    name = models.CharField(
        max_length=50,
        blank=True,
        verbose_name='Nome de Exibição',
        help_text='Caso não informado, o nome do arquivo será usado para preencher este campo.',
    )

    file = models.FileField(
        upload_to=upload_to,
        max_length=255,
        verbose_name='Arquivo',
        validators=[validators.validate_max_file_size],
    )

    geojson = models.JSONField(
        blank=True,
        null=True,
        verbose_name='GeoJSON',
        help_text='Este campo é gerado automaticamente ao subir um Shapefile e não deve ser alterado manualmente.',
    )

    validity = models.DateField(
        blank=True,
        null=True,
        verbose_name='Validade',
        help_text=(
            'Caso não informado e o nome do arquivo contém a data, ela será usada para preencher este campo.\n'
            'Exemplo: nome do arquivo CTF_02.05.2020.pdf, a data 02/05/2020 será usada.'
        ),
    )

    document_type = models.CharField(max_length=50, choices=DocumentType.choices, verbose_name='Tipo de Documento')
    visible = models.BooleanField(default=True, verbose_name='Visível')

    supplier = models.ForeignKey(
        'Supplier',
        on_delete=models.PROTECT,
        related_name='documents',
        verbose_name='Fornecedor',
    )

    @property
    def filename(self):
        return os.path.basename(self.file.name)

    def delete(self, *args, **kwargs):
        handle_file_cleanup_on_delete(self)
        super().delete(*args, **kwargs)

    def clean(self):
        # Caso não seja informado um nome de exibição
        # usar o próprio nome do arquivo.
        if not self.name:
            self.name = self.filename

        # Tenta extrair a data de validade do nome do
        # arquivo caso ela não seja informada.
        if (
            not self.validity
            and self.document_type != DocumentType.EXCEMPTION
            and self.document_type != DocumentType.CAR
            and self.document_type != DocumentType.SHAPEFILE
            and self.document_type != DocumentType.PROPERTY_SHAPEFILE
            and self.document_type != DocumentType.OTHER
        ):
            self.validity = dtutils.extract_date_from_text(self.filename)

            if not self.validity:
                raise ValidationError('Informe uma data de validade para este documento.')

        if self.document_type == DocumentType.SHAPEFILE or self.document_type == DocumentType.PROPERTY_SHAPEFILE:
            # Define a visibibilidade para todos
            # os Shapefiles como falso.
            self.visible = False

            if self.document_type == DocumentType.PROPERTY_SHAPEFILE:
                # Verificar se já existe um Shapefile de Propriedade
                # registrado para esse fornecedor de carvão.
                if Document.objects.filter(
                    document_type=DocumentType.PROPERTY_SHAPEFILE,
                    supplier=self.supplier,
                ).exists():
                    raise ValidationError('O fornecedor ja possui um Shapefile de Propriedade.')

            if self.file:
                try:
                    if self.file.name.lower().endswith('.zip'):
                        self.geojson = geojson.from_shapefile_zip(self.file)
                    else:
                        raise ValidationError('O arquivo enviado deve ser um arquivo ZIP válido.')

                except ValidationError as e:
                    raise e

        return super().clean()

    def save(self, *args, **kwargs):
        handle_file_cleanup(self)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.document_type} - {self.filename}'

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Documento'
        verbose_name_plural = 'Documentos'

gelfmp/models/supplier.py
from django.db import models
from django.db.models.query import QuerySet
from django.forms import ValidationError

from gelfmp.utils import validators
from gelfmp.utils.normalization import normalize_text_upper, normalize_to_numbers

from .base_model import BaseModel
from .charcoal_iqf import CharcoalIQF
from .choices import MaterialType, SupplierType
from .city_state import City, State
from .document import Document


class Supplier(BaseModel):
    corporate_name = models.CharField(
        max_length=200,
        verbose_name='Razão Social',
        unique=True,
        help_text='Insira nomes padronizados para evitar inconsistência, como o próprio nome que consta no CNPJ.',
    )

    rm_code = models.CharField(max_length=30, null=True, blank=True, unique=True, verbose_name='Código RM')
    active = models.BooleanField(default=True, verbose_name='Fornecedor Ativo')

    material_type = models.CharField(max_length=100, choices=MaterialType.choices, verbose_name='Tipo de Material')
    supplier_type = models.CharField(
        max_length=100,
        choices=SupplierType.choices,
        null=True,
        blank=True,
        verbose_name='Tipo de Fornecedor (Carvão)',
    )

    distance_in_meters = models.IntegerField(blank=True, null=True, verbose_name='Distância em Metros')
    address = models.CharField(max_length=255, blank=True, null=True, verbose_name='Endereço')
    state = models.ForeignKey(State, on_delete=models.PROTECT, related_name='suppliers', verbose_name='Estado')
    city = models.ForeignKey(City, on_delete=models.PROTECT, related_name='suppliers', verbose_name='Cidade')

    cep = models.CharField(
        max_length=10,
        validators=[validators.validate_cep],
        verbose_name='CEP',
    )

    latitude = models.DecimalField(
        max_digits=11,
        decimal_places=8,
        validators=[validators.validate_latitude],
        null=True,
        blank=True,
    )
    longitude = models.DecimalField(
        max_digits=11,
        decimal_places=8,
        validators=[validators.validate_longitude],
        null=True,
        blank=True,
    )

    state_registration = models.CharField(max_length=50, verbose_name='Inscrição Estadual', null=True, blank=True)
    municipal_registration = models.CharField(max_length=50, verbose_name='Inscrição Municipal', null=True, blank=True)
    xml_email = models.EmailField(verbose_name='Email XML', null=True, blank=True)

    cpf_cnpj = models.CharField(
        unique=True,
        max_length=18,
        validators=[validators.validate_cpf_cnpj],
        verbose_name='CPF ou CNPJ',
    )

    observations = models.TextField(
        max_length=2000,
        blank=True,
        null=True,
        verbose_name='Observações',
        help_text='Adicione informações adicionais ou observações relevantes.',
    )

    def get_visible_documents(self) -> QuerySet[Document]:
        return self.documents.filter(visible=True)

    def get_iqfs(self) -> models.Manager[CharcoalIQF]:
        return self.iqfs

    def is_charcoal_supplier(self):
        return self.material_type == MaterialType.CHARCOAL

    def clean(self):
        # Impede que o campo `Tipo de Fornecedor` seja
        # utilizado em fornecedores que não sejam de carvão.
        if self.supplier_type and self.material_type != MaterialType.CHARCOAL:
            raise ValidationError({
                'supplier_type': 'O campo `Tipo de Fornecedor` é exclusivo para fornecedores de carvão.'
            })

        # Garante que o campo `Tipo de Fornecedor` seja
        # preenchido caso seja um fornecedor de carvão.
        if self.material_type == MaterialType.CHARCOAL and not self.supplier_type:
            raise ValidationError({
                'supplier_type': 'O campo `Tipo de Fornecedor` é obrigatório para fornecedores de carvão.'
            })

        return super().clean()

    def save(self, *args, **kwargs):
        # Normaliza os campos para evitar inconsistência nos dados.
        self.corporate_name = normalize_text_upper(self.corporate_name)
        self.cpf_cnpj = normalize_to_numbers(self.cpf_cnpj)
        self.cep = normalize_to_numbers(self.cep)

        return super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        # Deleta detalhes de banco relacionados
        # ao fornecedor caso exista algum.
        if self.bank_details:
            self.bank_details.delete()

        super().delete(*args, **kwargs)

    class Meta:
        ordering = ['corporate_name']

        indexes = [
            models.Index(fields=['material_type']),
            models.Index(fields=['state']),
            models.Index(fields=['cpf_cnpj']),
        ]

        verbose_name = 'Fornecedor'
        verbose_name_plural = 'Fornecedores'

    def __str__(self):
        return self.corporate_name

templates/supplier/partials/supplier_aside_info.html
<div class="flex flex-col items-center bg-dark-100 shadow-md p-4 rounded-md w-full h-fit">
    {% load custom_filters %}
    <!-- Nome do fornecedor -->
    <h2 class="mb-6 font-bold text-center text-white text-xl">{{ supplier.corporate_name }}</h2>
    <table class="w-full text-[0.75rem] text-left text-slate-300">
        <tbody class="w-full h-fit">
            <!-- Município e Estado -->
            <tr class="border-dark-200 border-b w-full">
                <th class="px-4 py-2 font-medium text-slate-500">Município</th>
                <td class="text-right px-4 py-2">
                    <div class="flex justify-end items-center gap-2">
                        {% include "components/copyable_text.html" with value=supplier.city.name|add:" - "|add:supplier.state.abbr %}
                    </div>
                </td>
            </tr>
            <!-- CEP -->
            <tr class="border-dark-200 border-b">
                <th class="px-4 py-2 font-medium text-slate-500">CEP</th>
                <td class="text-right px-4 py-2">
                    <div class="flex justify-end items-center gap-2">
                        {% include "components/copyable_text.html" with value=supplier.cep %}
                    </div>
                </td>
            </tr>
            <!-- CPF/CNPJ -->
            <tr class="border-dark-200 border-b">
                <th class="px-4 py-2 font-medium text-slate-500">CPF/CNPJ</th>
                <td class="text-right px-4 py-2">
                    <div class="flex justify-end items-center gap-2">
                        {% include "components/copyable_text.html" with value=supplier.cpf_cnpj|format_cpf_cnpj %}
                    </div>
                </td>
            </tr>
            <!-- Tipo de Material -->
            <tr class="border-dark-200 border-b">
                <th class="px-4 py-2 font-medium text-slate-500">Tipo de Material</th>
                <td class="text-right px-4 py-2">
                    <div class="flex justify-end items-center gap-2">
                        <span>{{ supplier.material_type }}</span>
                    </div>
                </td>
            </tr>
            <!-- Código RM -->
            {% if supplier.rm_code %}
                <tr class="border-dark-200 border-b">
                    <th class="px-4 py-2 font-medium text-slate-500">Código RM</th>
                    <td class="text-right px-4 py-2">
                        <div class="flex justify-end items-center gap-2">
                            {% include "components/copyable_text.html" with value=supplier.rm_code %}
                        </div>
                    </td>
                </tr>
            {% endif %}
            <!-- Inscrição Estadual -->
            {% if supplier.state_registration %}
                <tr class="border-dark-200 border-b">
                    <th class="px-4 py-2 font-medium text-slate-500">Inscrição Estadual</th>
                    <td class="text-right px-4 py-2">
                        <div class="flex justify-end items-center gap-2">
                            {% include "components/copyable_text.html" with value=supplier.state_registration %}
                        </div>
                    </td>
                </tr>
            {% endif %}
            <!-- Inscrição Municipal -->
            {% if supplier.municipal_registration %}
                <tr class="border-dark-200 border-b">
                    <th class="px-4 py-2 font-medium text-slate-500">Inscrição Municipal</th>
                    <td class="text-right px-4 py-2">
                        <div class="flex justify-end items-center gap-2">
                            {% include "components/copyable_text.html" with value=supplier.municipal_registration %}
                        </div>
                    </td>
                </tr>
            {% endif %}
            <!-- Fornecedor Ativo -->
            <tr class="border-dark-200 border-b">
                <th class="px-4 py-2 font-medium text-slate-500">Fornecedor Ativo</th>
                <td class="text-right px-4 py-2">
                    <div class="flex justify-end items-center gap-2">
                        <span>
                            {% if supplier.active %}
                                Sim
                            {% else %}
                                Não
                            {% endif %}
                        </span>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
    <!-- Observações -->
    {% if supplier.observations %}
        <h2 class="m-4 text-slate-300">Observações</h2>
        <pre class="w-full text-center text-pretty text-slate-500 text-xs">{{ supplier.observations }}</pre>
    {% endif %}
    <!-- Link para Google Earth -->
    {% if supplier.latitude and supplier.longitude %}
        <div class="pt-2">
            <a href="https://earth.google.com/web/@{{ supplier.latitude|comma_to_dot }},{{ supplier.longitude|comma_to_dot }},50000d,35y,0h,0t,0r"
               target="_blank"
               rel="noopener noreferrer"
               class="flex items-center gap-2 mt-4 text-slate-500 hover:text-white transition-colors duration-200 group">
                <span class="group-hover:text-primary font-medium text-sm transition-colors">Ver no Google Earth</span>
            </a>
        </div>
    {% endif %}
</div>

templates/supplier/partials/supplier_bank_details.html
{% if supplier.bank_details %}
    <div class="bg-dark-100 shadow-md rounded-md min-h-fit overflow-x-auto">
        <!-- Título -->
        <h2 class="bg-dark-200 mb-2 p-2 font-medium text-center text-md text-slate-300 uppercase">Informações Bancárias</h2>
        <!-- Tabela de informações bancárias -->
        <table class="border-collapse mb-4 px-4 w-full h-fit text-[0.75rem] text-center text-slate-300">
            <thead class="border-dark-200 border-b">
                <tr>
                    <th class="px-4 py-2 font-medium text-slate-500">Nome do Banco</th>
                    <th class="px-4 py-2 font-medium text-slate-500">Código do Banco</th>
                    <th class="px-4 py-2 font-medium text-slate-500">Conta Corrente</th>
                    <th class="px-4 py-2 font-medium text-slate-500">Agência</th>
                    <th class="px-4 py-2 font-medium text-slate-500">CNPJ da Conta</th>
                </tr>
            </thead>
            <tbody class="w-full h-fit">
                <!-- Dados bancários do fornecedor -->
                {% for bd in supplier.bank_details.all %}
                    <tr class="border-dark-200">
                        <td class="px-4 py-2">{% include "components/copyable_text.html" with value=bd.bank_name %}</td>
                        <td class="px-4 py-2">{% include "components/copyable_text.html" with value=bd.bank_code %}</td>
                        <td class="px-4 py-2">
                            {% include "components/copyable_text.html" with value=bd.account_number %}
                        </td>
                        <td class="px-4 py-2">{% include "components/copyable_text.html" with value=bd.agency %}</td>
                        {% if bd.account_cnpj %}
                            <td class="px-4 py-2">{% include "components/copyable_text.html" with value=bd.account_cnpj %}</td>
                        {% else %}
                            <td class="px-4 py-2">-</td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endif %}

templates/supplier/partials/supplier_contacts.html
{% if contacts %}
    <div class="bg-dark-100 shadow-md rounded-md min-h-fit overflow-x-auto">
        <!-- Título -->
        <h2 class="bg-dark-200 mb-2 p-2 font-medium text-center text-md text-slate-300 uppercase">Contatos</h2>
        <!-- Tabela de contatos -->
        <table class="border-collapse mb-4 px-4 w-full h-fit text-[0.75rem] text-center text-slate-300">
            <thead class="border-dark-200 border-b">
                <tr>
                    <th class="px-4 py-2 font-medium text-slate-500">Tipo de Contato</th>
                    <th class="px-4 py-2 font-medium text-slate-500">Nome</th>
                    <th class="px-4 py-2 font-medium text-slate-500">Email</th>
                    <th class="px-4 py-2 font-medium text-slate-500">CPF</th>
                    <th class="px-4 py-2 font-medium text-slate-500">Telefone 01</th>
                    <th class="px-4 py-2 font-medium text-slate-500">Telefone 02</th>
                </tr>
            </thead>
            <tbody class="w-full h-fit">
                <!-- Iteração pelos contatos do fornecedor -->
                {% for contact in contacts %}
                    <tr class="border-dark-200 {% if not forloop.last %}border-b{% endif %}">
                        <!-- Tipo de Contato -->
                        <td class="px-4 py-2">
                            <span>{{ contact.get_contact_type_display }}</span>
                        </td>
                        <!-- Nome -->
                        <td class="px-4 py-2">{% include "components/copyable_text.html" with value=contact.name %}</td>
                        <!-- Email -->
                        <td class="px-4 py-2">
                            {% if contact.email %}
                                {% include "components/copyable_text.html" with value=contact.email %}
                            {% else %}
                                <span>-</span>
                            {% endif %}
                        </td>
                        <!-- CPF -->
                        <td class="px-4 py-2">
                            {% if contact.cpf %}
                                {% include "components/copyable_text.html" with value=contact.cpf %}
                            {% else %}
                                <span>-</span>
                            {% endif %}
                        </td>
                        <!-- Telefone Principal -->
                        <td class="px-4 py-2">
                            {% if contact.primary_phone %}
                                {% include "components/copyable_text.html" with value=contact.primary_phone %}
                            {% else %}
                                <span>-</span>
                            {% endif %}
                        </td>
                        <!-- Telefone Secundário -->
                        <td class="px-4 py-2">
                            {% if contact.secondary_phone %}
                                {% include "components/copyable_text.html" with value=contact.secondary_phone %}
                            {% else %}
                                <span>-</span>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endif %}

templates/supplier/partials/supplier_documents.html
{% load custom_filters %}
{% if documents %}
    <div class="bg-dark-100 shadow-md rounded-md min-h-fit overflow-x-auto">
        <!-- Título -->
        <h2 class="bg-dark-200 mb-2 p-2 font-medium text-center text-md text-slate-300 uppercase">Documentos</h2>
        <!-- Tabela de documentos -->
        <table class="border-collapse mb-4 px-4 w-full h-fit text-[0.75rem] text-center text-slate-300">
            <thead class="border-dark-200 border-b">
                <tr>
                    <th class="px-4 py-2 font-medium text-slate-500">Tipo do Documento</th>
                    <th class="px-4 py-2 font-medium text-slate-500">Arquivo</th>
                    <th class="px-4 py-2 font-medium text-slate-500">Validade</th>
                    <th class="px-4 py-2 font-medium text-slate-500">Status</th>
                </tr>
            </thead>
            <tbody class="w-full h-fit">
                <!-- Iteração pelos documentos do fornecedor -->
                {% for document in documents %}
                    <tr class="border-dark-200 {% if not forloop.last %}border-b{% endif %}">
                        <!-- Tipo de Documento -->
                        <td class="px-4 py-2">
                            <span>{{ document.get_document_type_display }}</span>
                        </td>
                        <!-- Arquivo -->
                        <td class="px-4 py-2">
                            {% if document.file %}
                                <a class="hover:text-slate-400"
                                   href="{{ document.file.url }}"
                                   target="_blank">{{ document.name }}</a>
                            {% else %}
                                -
                            {% endif %}
                        </td>
                        <!-- Validade do Documento -->
                        <td class="px-4 py-2">
                            <span>
                                {% if document.validity %}
                                    {{ document.validity }}
                                {% else %}
                                    -
                                {% endif %}
                            </span>
                        </td>
                        <!-- Status de Validade -->
                        <td class="px-4 py-2">
                            <span class="{{ document.validity|get_validity_status }}">
                                {% if document.validity %}
                                    {{ document.validity|get_validity_status }}
                                {% else %}
                                    -
                                {% endif %}
                            </span>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endif %}